parameters:
    locale: en


framework:
    session:
        gc_maxlifetime: 3600
        gc_probability: 1
        gc_divisor: 10
        save_path: "%kernel.var_dir%/session"
    translator: { fallback: "%locale%" }


twig:
    paths:
        "%kernel.root_dir%/../frontend/app/views": app


#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: Acme\AcmeBundle\Entity\User
